name: Docs

on:
  repository_dispatch:
    types: [docs]
  workflow_dispatch:

jobs:
  publish:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.x

      - name: Install Dependencies
        run: npm ci

      - name: Generate Docs
        run: npm run docs

      - name: Get Version From package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Deploy Docs to GH-Pages (version subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ${{ steps.package-version.outputs.current-version }}
          allow_empty_commit: true

      - name: Deploy Docs to GH-Pages (master subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: master
          allow_empty_commit: true
