name: On Push (Master)

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/pr.yml

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Generate Docs
        run: npm run docs

      - name: Get Version From package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Deploy Docs to GH-Pages (version subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ${{ steps.package-version.outputs.current-version }}
          allow_empty_commit: true

      - name: Deploy Docs to GH-Pages (master subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: master
          allow_empty_commit: true
